import {Component,ViewChild,ElementRef,ComponentFactoryResolver,ViewContainerRef,forwardRef,ContentChildren,QueryList} from '@angular/core';
import { extbase } from './ext.base';
// Ext Class - Ext.Audio
class extaudioMetaData {
	public static XTYPE: string = 'audio';
	public static INPUTNAMES: string[] = [
		'alwaysOnTop',
		'autoPause',
		'autoResume',
		'axisLock',
		'baseCls',
		'bind',
		'border',
		'bottom',
		'centered',
		'cls',
		'contentEl',
		'controller',
		'data',
		'defaultListenerScope',
		'disabled',
		'docked',
		'draggable',
		'enableControls',
		'enterAnimation',
		'exitAnimation',
		'flex',
		'floated',
		'fullscreen',
		'height',
		'hidden',
		'hideAnimation',
		'hideOnMaskTap',
		'html',
		'id',
		'itemId',
		'keyMap',
		'keyMapEnabled',
		'keyMapTarget',
		'left',
		'listeners',
		'loop',
		'margin',
		'maxHeight',
		'maxWidth',
		'media',
		'minHeight',
		'minWidth',
		'modal',
		'muted',
		'padding',
		'plugins',
		'preload',
		'publishes',
		'record',
		'reference',
		'relative',
		'renderTo',
		'right',
		'scrollable',
		'session',
		'shadow',
		'shim',
		'showAnimation',
		'style',
		'styleHtmlCls',
		'styleHtmlContent',
		'toFrontOnShow',
		'tooltip',
		'top',
		'touchAction',
		'tpl',
		'tplWriteMode',
		'translatable',
		'twoWayBindable',
		'ui',
		'url',
		'useBodyElement',
		'userCls',
		'viewModel',
		'volume',
		'width',
		'x',
		'xtype',
		'y',
		'zIndex',
		'fit',
		'config'
];
	public static OUTPUTS: any[] = [
		{name:'added',parameters:'audio,container,index'},
		{name:'beforehide',parameters:'audio'},
		{name:'beforeorientationchange',parameters:''},
		{name:'beforeshow',parameters:'audio'},
		{name:'beforetofront',parameters:'audio'},
		{name:'destroy',parameters:''},
		{name:'ended',parameters:'audio,time'},
		{name:'erased',parameters:'audio'},
		{name:'floatingchange',parameters:'audio,positioned'},
		{name:'fullscreen',parameters:'audio'},
		{name:'hide',parameters:'audio'},
		{name:'initialize',parameters:'audio'},
		{name:'moved',parameters:'audio,container,toIndex,fromIndex'},
		{name:'mutedchange',parameters:'audio,muted'},
		{name:'orientationchange',parameters:''},
		{name:'painted',parameters:'element'},
		{name:'pause',parameters:'audio,time'},
		{name:'play',parameters:'audio'},
		{name:'positionedchange',parameters:'audio,positioned'},
		{name:'removed',parameters:'audio,container,index'},
		{name:'resize',parameters:'element'},
		{name:'show',parameters:'audio'},
		{name:'stop',parameters:'audio'},
		{name:'timeupdate',parameters:'audio,time'},
		{name:'tofront',parameters:'audio'},
		{name:'updatedata',parameters:'audio,newData'},
		{name:'volumechange',parameters:'audio,volume'},
		{name:'ready',parameters:''}
];
	public static OUTPUTNAMES: string[] = [
		'added',
		'beforehide',
		'beforeorientationchange',
		'beforeshow',
		'beforetofront',
		'destroy',
		'ended',
		'erased',
		'floatingchange',
		'fullscreen',
		'hide',
		'initialize',
		'moved',
		'mutedchange',
		'orientationchange',
		'painted',
		'pause',
		'play',
		'positionedchange',
		'removed',
		'resize',
		'show',
		'stop',
		'timeupdate',
		'tofront',
		'updatedata',
		'volumechange',
		'ready'
];
}
@Component({
  selector: 'ext-' + extaudioMetaData.XTYPE,
	inputs: extaudioMetaData.INPUTNAMES,
	outputs: extaudioMetaData.OUTPUTNAMES,
	providers: [{provide: extbase, useExisting: forwardRef(() => extaudio)}],
	template: '<template #dynamic></template>'
})
export class extaudio extends extbase {
	constructor(eRef:ElementRef,resolver:ComponentFactoryResolver,vcRef:ViewContainerRef) {
		super(eRef,resolver,vcRef,extaudioMetaData);
	}
	@ContentChildren(extbase,{read:ViewContainerRef}) extbaseRef:QueryList<ViewContainerRef>;
	@ViewChild('dynamic',{read:ViewContainerRef}) dynamicRef:ViewContainerRef;
	ngAfterContentInit() {this.AfterContentInit(this.extbaseRef);}
	ngOnInit() {this.OnInit(this.dynamicRef,extaudioMetaData);}
}
