import {Component,ViewChild,ElementRef,ComponentFactoryResolver,ViewContainerRef,forwardRef,ContentChildren,QueryList} from '@angular/core';
import { extbase } from './ext.base';
// Ext Class - Ext.field.Text
class exttextfieldMetaData {
	public static XTYPE: string = 'textfield';
	public static INPUTNAMES: string[] = [
		'alwaysOnTop',
		'autoCapitalize',
		'autoComplete',
		'autoCorrect',
		'axisLock',
		'baseCls',
		'bind',
		'bodyAlign',
		'border',
		'bottom',
		'centered',
		'clearIcon',
		'cls',
		'component',
		'contentEl',
		'controller',
		'data',
		'defaultListenerScope',
		'disabled',
		'docked',
		'draggable',
		'enterAnimation',
		'exitAnimation',
		'flex',
		'floated',
		'fullscreen',
		'height',
		'hidden',
		'hideAnimation',
		'hideOnMaskTap',
		'html',
		'id',
		'inputCls',
		'inputType',
		'isFocused',
		'itemId',
		'keyMap',
		'keyMapEnabled',
		'keyMapTarget',
		'label',
		'labelAlign',
		'labelCls',
		'labelTextAlign',
		'labelWidth',
		'labelWrap',
		'left',
		'listeners',
		'margin',
		'maxHeight',
		'maxLength',
		'maxWidth',
		'minHeight',
		'minWidth',
		'modal',
		'name',
		'padding',
		'placeHolder',
		'plugins',
		'publishes',
		'readOnly',
		'record',
		'reference',
		'relative',
		'renderTo',
		'required',
		'right',
		'scrollable',
		'session',
		'shadow',
		'shim',
		'showAnimation',
		'style',
		'styleHtmlCls',
		'styleHtmlContent',
		'tabIndex',
		'textAlign',
		'toFrontOnShow',
		'tooltip',
		'top',
		'touchAction',
		'tpl',
		'tplWriteMode',
		'translatable',
		'triggers',
		'twoWayBindable',
		'ui',
		'useBodyElement',
		'userCls',
		'value',
		'viewModel',
		'width',
		'x',
		'xtype',
		'y',
		'zIndex',
		'platformConfig',
		'responsiveConfig',
		'fitToParent',
		'config'
];
	public static OUTPUTS: any[] = [
		{name:'action',parameters:'textfield,e'},
		{name:'added',parameters:'textfield,container,index'},
		{name:'beforehide',parameters:'textfield'},
		{name:'beforeorientationchange',parameters:''},
		{name:'beforeshow',parameters:'textfield'},
		{name:'beforetofront',parameters:'textfield'},
		{name:'blur',parameters:'textfield,e'},
		{name:'change',parameters:'textfield,newValue,oldValue'},
		{name:'clearicontap',parameters:'textfield,input,e'},
		{name:'destroy',parameters:''},
		{name:'erased',parameters:'textfield'},
		{name:'floatingchange',parameters:'textfield,positioned'},
		{name:'focus',parameters:'textfield,e'},
		{name:'fullscreen',parameters:'textfield'},
		{name:'hide',parameters:'textfield'},
		{name:'initialize',parameters:'textfield'},
		{name:'keyup',parameters:'textfield,e'},
		{name:'mousedown',parameters:'textfield,e'},
		{name:'moved',parameters:'textfield,container,toIndex,fromIndex'},
		{name:'orientationchange',parameters:''},
		{name:'painted',parameters:'element'},
		{name:'paste',parameters:'textfield,e'},
		{name:'positionedchange',parameters:'textfield,positioned'},
		{name:'removed',parameters:'textfield,container,index'},
		{name:'resize',parameters:'element'},
		{name:'show',parameters:'textfield'},
		{name:'tofront',parameters:'textfield'},
		{name:'updatedata',parameters:'textfield,newData'},
		{name:'ready',parameters:''}
];
	public static OUTPUTNAMES: string[] = [
		'action',
		'added',
		'beforehide',
		'beforeorientationchange',
		'beforeshow',
		'beforetofront',
		'blur',
		'change',
		'clearicontap',
		'destroy',
		'erased',
		'floatingchange',
		'focus',
		'fullscreen',
		'hide',
		'initialize',
		'keyup',
		'mousedown',
		'moved',
		'orientationchange',
		'painted',
		'paste',
		'positionedchange',
		'removed',
		'resize',
		'show',
		'tofront',
		'updatedata',
		'ready'
];
}
@Component({
  selector: 'ext-' + exttextfieldMetaData.XTYPE,
	inputs: exttextfieldMetaData.INPUTNAMES,
	outputs: exttextfieldMetaData.OUTPUTNAMES,
	providers: [{provide: extbase, useExisting: forwardRef(() => exttextfield)}],
	template: '<template #dynamic></template>'
})
export class exttextfield extends extbase {
	constructor(eRef:ElementRef,resolver:ComponentFactoryResolver,vcRef:ViewContainerRef) {
		super(eRef,resolver,vcRef,exttextfieldMetaData);
	}
	@ContentChildren(extbase,{read:ViewContainerRef}) extbaseRef:QueryList<ViewContainerRef>;
	@ViewChild('dynamic',{read:ViewContainerRef}) dynamicRef:ViewContainerRef;
	ngAfterContentInit() {this.AfterContentInit(this.extbaseRef);}
	ngOnInit() {this.OnInit(this.dynamicRef,exttextfieldMetaData);}
}
