import {Component,ViewChild,ElementRef,ComponentFactoryResolver,ViewContainerRef,forwardRef,ContentChildren,QueryList} from '@angular/core';
import { extbase } from './ext.base';
// Ext Class - Ext.field.Input
class extinputMetaData {
	public static XTYPE: string = 'input';
	public static INPUTNAMES: string[] = [
		'alwaysOnTop',
		'autoCapitalize',
		'autoComplete',
		'autoCorrect',
		'axisLock',
		'baseCls',
		'bind',
		'border',
		'bottom',
		'centered',
		'checked',
		'cls',
		'contentEl',
		'controller',
		'data',
		'defaultListenerScope',
		'disabled',
		'docked',
		'draggable',
		'enterAnimation',
		'exitAnimation',
		'fastFocus',
		'flex',
		'floated',
		'fullscreen',
		'height',
		'hidden',
		'hideAnimation',
		'hideOnMaskTap',
		'html',
		'id',
		'isFocused',
		'itemId',
		'keyMap',
		'keyMapEnabled',
		'keyMapTarget',
		'left',
		'listeners',
		'margin',
		'maxHeight',
		'maxLength',
		'maxRows',
		'maxValue',
		'maxWidth',
		'minHeight',
		'minValue',
		'minWidth',
		'modal',
		'name',
		'originalValue',
		'padding',
		'pattern',
		'placeHolder',
		'plugins',
		'publishes',
		'readOnly',
		'record',
		'reference',
		'relative',
		'renderTo',
		'right',
		'scrollable',
		'session',
		'shadow',
		'shim',
		'showAnimation',
		'startValue',
		'stepValue',
		'style',
		'styleHtmlCls',
		'styleHtmlContent',
		'tabIndex',
		'toFrontOnShow',
		'tooltip',
		'top',
		'touchAction',
		'tpl',
		'tplWriteMode',
		'translatable',
		'twoWayBindable',
		'type',
		'ui',
		'useBodyElement',
		'useMask',
		'userCls',
		'value',
		'viewModel',
		'width',
		'x',
		'xtype',
		'y',
		'zIndex',
		'platformConfig',
		'responsiveConfig',
		'fitToParent',
		'config'
];
	public static OUTPUTS: any[] = [
		{name:'added',parameters:'input,container,index'},
		{name:'beforehide',parameters:'input'},
		{name:'beforeorientationchange',parameters:''},
		{name:'beforeshow',parameters:'input'},
		{name:'beforetofront',parameters:'input'},
		{name:'blur',parameters:'e'},
		{name:'click',parameters:'e'},
		{name:'destroy',parameters:''},
		{name:'erased',parameters:'input'},
		{name:'floatingchange',parameters:'input,positioned'},
		{name:'focus',parameters:'e'},
		{name:'fullscreen',parameters:'input'},
		{name:'hide',parameters:'input'},
		{name:'initialize',parameters:'input'},
		{name:'keyup',parameters:'e'},
		{name:'masktap',parameters:'input,e'},
		{name:'mousedown',parameters:'e'},
		{name:'moved',parameters:'input,container,toIndex,fromIndex'},
		{name:'orientationchange',parameters:''},
		{name:'painted',parameters:'element'},
		{name:'paste',parameters:'e'},
		{name:'positionedchange',parameters:'input,positioned'},
		{name:'removed',parameters:'input,container,index'},
		{name:'resize',parameters:'element'},
		{name:'show',parameters:'input'},
		{name:'tofront',parameters:'input'},
		{name:'updatedata',parameters:'input,newData'},
		{name:'ready',parameters:''}
];
	public static OUTPUTNAMES: string[] = [
		'added',
		'beforehide',
		'beforeorientationchange',
		'beforeshow',
		'beforetofront',
		'blur',
		'click',
		'destroy',
		'erased',
		'floatingchange',
		'focus',
		'fullscreen',
		'hide',
		'initialize',
		'keyup',
		'masktap',
		'mousedown',
		'moved',
		'orientationchange',
		'painted',
		'paste',
		'positionedchange',
		'removed',
		'resize',
		'show',
		'tofront',
		'updatedata',
		'ready'
];
}
@Component({
  selector: 'ext-' + extinputMetaData.XTYPE,
	inputs: extinputMetaData.INPUTNAMES,
	outputs: extinputMetaData.OUTPUTNAMES,
	providers: [{provide: extbase, useExisting: forwardRef(() => extinput)}],
	template: '<template #dynamic></template>'
})
export class extinput extends extbase {
	constructor(eRef:ElementRef,resolver:ComponentFactoryResolver,vcRef:ViewContainerRef) {
		super(eRef,resolver,vcRef,extinputMetaData);
	}
	@ContentChildren(extbase,{read:ViewContainerRef}) extbaseRef:QueryList<ViewContainerRef>;
	@ViewChild('dynamic',{read:ViewContainerRef}) dynamicRef:ViewContainerRef;
	ngAfterContentInit() {this.AfterContentInit(this.extbaseRef);}
	ngOnInit() {this.OnInit(this.dynamicRef,extinputMetaData);}
}
