import {Component,ViewChild,ElementRef,ComponentFactoryResolver,ViewContainerRef,forwardRef,ContentChildren,QueryList} from '@angular/core';
import { xbase } from './x.base';
// Ext Class - Ext.field.TextAreaInput
class xtextareainputMetaData {
	public static XTYPE: string = 'textareainput';
	public static INPUTNAMES: string[] = [
		'alwaysOnTop',
		'autoCapitalize',
		'autoComplete',
		'autoCorrect',
		'axisLock',
		'baseCls',
		'bind',
		'border',
		'bottom',
		'centered',
		'checked',
		'cls',
		'contentEl',
		'controller',
		'data',
		'defaultListenerScope',
		'disabled',
		'docked',
		'draggable',
		'enterAnimation',
		'exitAnimation',
		'fastFocus',
		'flex',
		'floated',
		'fullscreen',
		'height',
		'hidden',
		'hideAnimation',
		'hideOnMaskTap',
		'html',
		'id',
		'isFocused',
		'itemId',
		'keyMap',
		'keyMapEnabled',
		'keyMapTarget',
		'left',
		'listeners',
		'margin',
		'maxHeight',
		'maxLength',
		'maxRows',
		'maxValue',
		'maxWidth',
		'minHeight',
		'minValue',
		'minWidth',
		'modal',
		'name',
		'originalValue',
		'padding',
		'pattern',
		'placeHolder',
		'plugins',
		'publishes',
		'readOnly',
		'record',
		'reference',
		'relative',
		'renderTo',
		'right',
		'scrollable',
		'session',
		'shadow',
		'shim',
		'showAnimation',
		'startValue',
		'stepValue',
		'style',
		'styleHtmlCls',
		'styleHtmlContent',
		'tabIndex',
		'toFrontOnShow',
		'tooltip',
		'top',
		'touchAction',
		'tpl',
		'tplWriteMode',
		'translatable',
		'twoWayBindable',
		'type',
		'ui',
		'useBodyElement',
		'useMask',
		'userCls',
		'value',
		'viewModel',
		'width',
		'x',
		'xtype',
		'y',
		'zIndex',
		'platformConfig',
		'responsiveConfig',
		'fittoparent',
		'config'
];
	public static OUTPUTS: any[] = [
		{name:'added',parameters:'textareainput,container,index'},
		{name:'beforehide',parameters:'textareainput'},
		{name:'beforeorientationchange',parameters:''},
		{name:'beforeshow',parameters:'textareainput'},
		{name:'beforetofront',parameters:'textareainput'},
		{name:'blur',parameters:'e'},
		{name:'click',parameters:'e'},
		{name:'destroy',parameters:''},
		{name:'erased',parameters:'textareainput'},
		{name:'floatingchange',parameters:'textareainput,positioned'},
		{name:'focus',parameters:'e'},
		{name:'fullscreen',parameters:'textareainput'},
		{name:'hide',parameters:'textareainput'},
		{name:'initialize',parameters:'textareainput'},
		{name:'keyup',parameters:'e'},
		{name:'masktap',parameters:'textareainput,e'},
		{name:'mousedown',parameters:'e'},
		{name:'moved',parameters:'textareainput,container,toIndex,fromIndex'},
		{name:'orientationchange',parameters:''},
		{name:'painted',parameters:'element'},
		{name:'paste',parameters:'e'},
		{name:'positionedchange',parameters:'textareainput,positioned'},
		{name:'removed',parameters:'textareainput,container,index'},
		{name:'resize',parameters:'element'},
		{name:'show',parameters:'textareainput'},
		{name:'tofront',parameters:'textareainput'},
		{name:'updatedata',parameters:'textareainput,newData'},
		{name:'ready',parameters:''}
];
	public static OUTPUTNAMES: string[] = [
		'added',
		'beforehide',
		'beforeorientationchange',
		'beforeshow',
		'beforetofront',
		'blur',
		'click',
		'destroy',
		'erased',
		'floatingchange',
		'focus',
		'fullscreen',
		'hide',
		'initialize',
		'keyup',
		'masktap',
		'mousedown',
		'moved',
		'orientationchange',
		'painted',
		'paste',
		'positionedchange',
		'removed',
		'resize',
		'show',
		'tofront',
		'updatedata',
		'ready'
];
}
@Component({
  selector: 'x-' + xtextareainputMetaData.XTYPE,
	inputs: xtextareainputMetaData.INPUTNAMES,
	outputs: xtextareainputMetaData.OUTPUTNAMES,
	providers: [{provide: xbase, useExisting: forwardRef(() => xtextareainput)}],
	template: '<template #dynamic></template>'
})
export class xtextareainput extends xbase {
	constructor(eRef:ElementRef,resolver:ComponentFactoryResolver,vcRef:ViewContainerRef) {
		super(eRef,resolver,vcRef,xtextareainputMetaData);
	}
	//@ContentChildren(xbase,{read:ViewContainerRef}) extbaseRef:QueryList<ViewContainerRef>;
	@ContentChildren(xbase,{read: xbase}) extbaseRef: QueryList<xbase>;
	@ViewChild('dynamic',{read:ViewContainerRef}) dynamicRef:ViewContainerRef;
	ngAfterContentInit() {this.AfterContentInit(this.extbaseRef);}
	ngOnInit() {this.OnInit(this.dynamicRef,xtextareainputMetaData);}
}
